
# install brew, fail by make
#	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

all:
	brew bundle
backup:
	brew bundle dump --describe --force --file="~/.brew/Brewfile"
